#php artisan make:cast Cast
#php artisan make:channel Channel
#php artisan make:command Command
#php artisan make:component  Component
#php artisan make:controller Controller
#php artisan make:event Event
#php artisan make:exception Exception
#php artisan make:factory Factory
#php artisan make:job Job
#php artisan make:listener Listener
#php artisan make:mail Mail
#php artisan make:middleware Middleware
#php artisan make:migration Migration
#php artisan make:model Model2
#php artisan make:notification Notification
#php artisan make:observer Observer
#php artisan make:policy Policy
#php artisan make:provider Provider
#php artisan make:request Request
#php artisan make:resource Resource
#php artisan make:rule Rule
#php artisan make:scope Scope
#php artisan make:seeder Seeder
#php artisan make:test Test
php artisan make:model Table12
php artisan make:controller MainController

run C:\Windows\system32\cmd.exe cd C:\Users\DmitriyBalovnev\PhpstormProjects\nativephp\laravel
